# Generated by Django 3.1.4 on 2020-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDetails',
            fields=[
                ('ExpenseID', models.IntegerField(primary_key=True, serialize=False)),
                ('ExpenseName', models.CharField(max_length=80)),
                ('Quantity', models.IntegerField()),
                ('UnitCost', models.FloatField()),
                ('TotalCost', models.FloatField()),
                ('ExpenseGroup', models.CharField(max_length=20)),
                ('Year', models.IntegerField()),
                ('RecordDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('Year', models.IntegerField(primary_key=True, serialize=False)),
                ('TotalCost', models.FloatField()),
                ('RecordDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('IncomeID', models.IntegerField(primary_key=True, serialize=False)),
                ('Revenue', models.FloatField()),
                ('Year', models.IntegerField()),
                ('ReceivedDate', models.DateTimeField()),
                ('RecordDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
